// ui.js - the platform's UI strings, taken verbatim by extract_ui.py.
// Every key, en/ka/ru, exactly as index.html has them. DO NOT EDIT: re-run the
// extractor. A hand-maintained copy of this object is how the menu ended up
// showing the word "undefined" to Georgian diners.
//
// `window.UI` because that is what the ported viewer, the AR overlay and the
// basket all read - `UI[window.__lang].loading` and forty-one more.

window.UI = {
    en: {
        tagline:   'Taste the Wild',
        viewAR:    'VIEW ON TABLE',
        view3D:    'VIEW IN 3D',
        loading:   'Loading...',
        close:     'Close',
        tip:       'Drag to rotate',
        spin:      'Auto-spin',
        placeHint: 'Scan a well-lit, textured table slowly, then tap to place',
        moveHint:  'Drag to rotate · Pinch to scale',
        exitAR:    'Exit Model view',
        placeAgain:'Place Again',
        hintStep1: 'STEP 1 OF 2',
        hintScan:  'Slowly scan a well-lit, textured table',
        hintStep2: 'STEP 2 OF 2',
        hintTap:   'Tap to place your dish',
        coachScan:    'Find a table',
        coachScanSub: 'Move your phone slowly over a flat, textured table',
        coachFound:   'Surface Found!',
        coachFoundSub:'Ready to place your dish',
        langBtn:   'ქარ',
        themeDay:  'Day',
        themeNight:'Night',
        carouselBtn:  'CAROUSEL',
    singleBtn:    'SINGLE ITEM',
    onTable:      'ON TABLE',
    floating:     'FLOATING',
    addBtn:       'ADD',
    basketTitle:  'Basket',
    emptyBasket:  'Your basket is empty',
    total:        'Total',
    clearBasket:  'Clear',
    showWaiter:   'Show to staff',
    waiterHint:   'Staff scans this to get your order instantly',
    readyBtn:     '✓ Ready to Order',
    readyDone:    '✓ Order Noted!',
    hideUI:       'HIDE UI',
    showUI:       'SHOW UI',
    arNoUsdz:     'iPhone AR needs a USDZ model. Showing 3D instead.',
    arNoModel:    '3D model is not available for this item.',
    arModelMissing:'Could not load the 3D model. Showing 3D instead.',
    arFailed:     'Could not start AR. Showing 3D instead.',
    arUnsupported:'AR is not available on this device. Showing 3D instead.',
    },
    ka: {
        tagline:   'გასინჯე ველური გემო',
        viewAR:    'ᲛᲐᲒᲘᲓᲐᲖᲔ ᲜᲐᲮᲕᲐ',
        view3D:    '3D-ში ᲜᲐᲮᲕᲐ',
        loading:   'იტვირთება...',
        close:     'დახურვა',
        tip:       'გაასრიალეთ მოსაბრუნებლად',
        spin:      'ავტო-ტრიალი',
        placeHint: 'მიუშვირე კარგად განათებულ, ტექსტურიან ბრტყელ მაგიდას და ნელა ამოძრავე',
        moveHint:  'გასაბრუნებლად გაასრიალე · პინჩი მასშტაბისთვის',
        exitAR:    'მოდელის დახურვა',
        placeAgain:'ხელახლა დადება',
        hintStep1: 'ნაბიჯი 1 / 2',
        hintScan:  'ნელა დაასკანერე განათებული, ტექსტურიანი მაგიდა',
        hintStep2: 'ნაბიჯი 2 / 2',
        hintTap:   'შეეხე ეკრანს მოთავსებისთვის',
        coachScan:    'მაგიდის ძიება',
        coachScanSub: 'ნელა ამოძრავეთ ტელეფონი ტექსტურიან ბრტყელ მაგიდაზე',
        coachFound:   'ზედაპირი ნაპოვნია!',
        coachFoundSub:'მზადაა კერძის დასადებად',
        langBtn:   'RU',
        themeDay:  'ნათელი თემა',
        themeNight:'მუქი თემა',
        carouselBtn:  'კარუსელი',
    singleBtn:    'ცალი',
    onTable:      'მაგიდაზე ტექსტი ',
    floating:     'მოლივლივე ტექსტი',
    addBtn:       'დამატება',
    basketTitle:  'კალათა',
    emptyBasket:  'კალათა ცარიელია',
    total:        'სულ',
    clearBasket:  'გასუფთავება',
    showWaiter:   'აჩვენეთ სერვისის თანამშრომელს',
    waiterHint:   'სერვისის თანამშრომელი დაასკანერებს და მყისვე მიიღებს შენს შეკვეთას',
    readyBtn:     '✓ შეკვეთა მზადაა',
    readyDone:    '✓ მიღებულია!',
    hideUI:       'UI დამალვა',
    showUI:       'UI ჩვენება',
    arNoUsdz:     'iPhone-ზე AR-ს USDZ მოდელი სჭირდება. იხსნება 3D.',
    arNoModel:    'ამ ნივთისთვის 3D მოდელი არ არის.',
    arModelMissing:'3D მოდელი ვერ ჩაიტვირთა. იხსნება 3D.',
    arFailed:     'AR ვერ გაეშვა. იხსნება 3D.',
    arUnsupported:'ამ მოწყობილობაზე AR მიუწვდომელია. იხსნება 3D.',
    },
    ru: {
        tagline:   'Попробуй дикий вкус',
        viewAR:    'ПОКАЗАТЬ НА СТОЛЕ',
        view3D:    'СМОТРЕТЬ В 3D',
        loading:   'Загрузка...',
        close:     'Закрыть',
        tip:       'Проведите пальцем, чтобы повернуть',
        spin:      'Автовращение',
        placeHint: 'Наведите на хорошо освещённый стол с текстурой и медленно двигайте телефон',
        moveHint:  'Проведите пальцем — поворот · Сведите пальцы — масштаб',
        exitAR:    'Закрыть модель',
        placeAgain:'Разместить снова',
        hintStep1: 'ШАГ 1 ИЗ 2',
        hintScan:  'Медленно наведите на освещённый стол с текстурой',
        hintStep2: 'ШАГ 2 ИЗ 2',
        hintTap:   'Коснитесь экрана, чтобы разместить блюдо',
        coachScan:    'Найдите стол',
        coachScanSub: 'Медленно двигайте телефон над плоским столом с текстурой',
        coachFound:   'Поверхность найдена!',
        coachFoundSub:'Готово к размещению блюда',
        langBtn:   'EN',
        themeDay:  'Светлая тема',
        themeNight:'Тёмная тема',
        carouselBtn:  'КАРУСЕЛЬ',
        singleBtn:    'ОДНО БЛЮДО',
        onTable:      'НА СТОЛЕ',
        floating:     'В ВОЗДУХЕ',
        addBtn:       'ДОБАВИТЬ',
        basketTitle:  'Корзина',
        emptyBasket:  'Ваша корзина пуста',
        total:        'Итого',
        clearBasket:  'Очистить',
        showWaiter:   'Показать официанту',
        waiterHint:   'Официант отсканирует и сразу получит ваш заказ',
        readyBtn:     '✓ Заказ готов',
        readyDone:    '✓ Заказ принят!',
        hideUI:       'Скрыть интерфейс',
        showUI:       'Показать интерфейс',
        arNoUsdz:     'Для AR на iPhone нужна модель USDZ. Открываем 3D.',
        arNoModel:    'Для этого блюда 3D-модель недоступна.',
        arModelMissing:'Не удалось загрузить 3D-модель. Открываем 3D.',
        arFailed:     'Не удалось запустить AR. Открываем 3D.',
        arUnsupported:'AR недоступен на этом устройстве. Открываем 3D.',
    }
};
