#!/usr/bin/env python3
"""Turn .env into the env-vars file `gcloud run deploy` wants.

    python deploy/make_env_yaml.py

Writes `deploy/env.yaml`, which is gitignored for the same reason .env is: it contains
the Meshy key, the R2 keys and the shared Studio passwords in plain text. **Nothing here
prints a value.** It reports names and lengths only, so the output can be pasted into a
chat without rotating a key afterwards - which has already had to happen once.

The alternative is Secret Manager, and that is the right answer once more than one
service reads these. For one service and five people, a gitignored file next to the one
that already exists is the same trust boundary and one less thing to keep in sync.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / ".env"
DST = ROOT / "deploy" / "env.yaml"

# Everything the container reads. JOBS and MEMORY_LIMIT_MB are deliberately not here:
# inline is the default, and the memory limit is read from cgroups at runtime rather
# than being told to the process by a human who might be wrong.
WANTED = [
    "MESHY_API_KEY",
    "STUDIO_USERS",
    "R2_ENDPOINT",
    "R2_ACCESS_KEY_ID",
    "R2_SECRET_ACCESS_KEY",
    "R2_BUCKET_PHOTOS",
    "R2_BUCKET_MODELS",
]


def _quote(value: str) -> str:
    """YAML-safe double-quoted scalar. Keys contain / and + often enough to matter."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    if not SRC.exists():
        print(f"No {SRC}. Nothing to convert.")
        return 1

    found: dict[str, str] = {}
    for line in SRC.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key, value = key.strip(), value.strip().strip('"').strip("'")
        if key in WANTED and value:
            found[key] = value

    missing = [k for k in WANTED if k not in found]
    lines = [
        "# Generated by deploy/make_env_yaml.py from .env. Gitignored - it holds secrets.",
        "# Regenerate after rotating any key, then redeploy.",
    ]
    lines += [f"{k}: {_quote(found[k])}" for k in WANTED if k in found]
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"wrote {DST.relative_to(ROOT)}")
    for k in WANTED:
        state = f"{len(found[k])} chars" if k in found else "MISSING"
        print(f"  {k:24} {state}")
    if missing:
        print(f"\n{len(missing)} missing. The service will start but "
              f"{'storage will fall back to local disk' if any(m.startswith('R2') for m in missing) else 'generation or auth will fail'}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
