#!/usr/bin/env python3
"""Turn the verbatim ported files into a module the renderer can inline.

    python menu/render/build_ported.py

`menu/render/ported/` holds code lifted from the live platform's `index.html` - the 3D
modal, the thumbnail upgrade, the AR routing and the WebXR carousel. It is kept as real
`.js`/`.css`/`.html` files rather than pasted into a template literal for two reasons:

  it stays REVIEWABLE and diffable against the source it came from, so re-porting after
  the platform changes is a diff rather than an archaeology exercise;

  and a template literal is where the backticks bite. A single one inside `String.raw`
  ends the literal and the file fails to parse pointing dozens of lines from the cause -
  which cost three separate debugging rounds in one session before this existed.

The generated module is committed too, so a Cloudflare Worker build needs no Python and
`render.mjs` has no filesystem access at runtime.

**Do not edit `ported/viewer.js` or `ported/xr.js`.** They are production's code, byte for
byte, and the whole value of taking them is that they already work on real phones in real
restaurants. Everything we need to change lives in `ported/shim.js`.
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "ported"
OUT = HERE / "ported.mjs"

# Order matters at runtime: xr defines window.XR, the shim defines what viewer.js expects,
# viewer.js then wires the modal and AR on top of both.
# full.css is the platform's ENTIRE stylesheet, verbatim. Not a subset: a subset of a
# cascade-dependent language is a different stylesheet, which is how the last four
# bugs happened. See extract_css.py.
FILES = ["full.css", "viewer.html", "xr.js", "shim.js", "viewer.js", "page.js"]

# Every template's rules and every preset's values. Both are DATA - the point of
# MENU-PLATFORM 2.2 is that a restaurant look is a row, not a branch - so each is
# emitted as one map rather than a constant per template.
TEMPLATE_DIR = SRC / "templates"
PRESETS = SRC / "presets.json"

HEADER = '''// GENERATED by menu/render/build_ported.py - do not edit.
//
// The contents of menu/render/ported/*, as strings, so render.mjs can inline them with
// no filesystem and no bundler. Edit the files in ported/ and re-run the generator.
//
// viewer.js and xr.js are VERBATIM from the live platform. shim.js is the only adapter.

'''


def main() -> int:
    missing = [f for f in FILES if not (SRC / f).is_file()]
    if missing:
        print("missing:", ", ".join(missing))
        return 1

    parts = [HEADER]
    for name in FILES:
        body = (SRC / name).read_text(encoding="utf-8")
        var = name.replace(".", "_").upper()
        # json.dumps, not a template literal: it escapes backticks, backslashes and
        # newlines correctly and cannot be terminated early by the content.
        parts.append(f"export const {var} = {json.dumps(body)};\n")
        print(f"  {name:14} {len(body):>7,} chars -> {var}")

    tpl = {}  # template CSS now lives inside full.css; kept for the API
    for f in sorted(TEMPLATE_DIR.glob('*.css')):
        tpl[f.stem] = f.read_text(encoding='utf-8')
    parts.append(f'export const TEMPLATE_CSS = {json.dumps(tpl)};' + chr(10))
    print(f"  {'templates/*.css':14} {len(tpl):>7} files -> TEMPLATE_CSS")

    presets = json.loads(PRESETS.read_text(encoding='utf-8')) if PRESETS.is_file() else {}
    parts.append(f'export const PRESETS = {json.dumps(presets)};' + chr(10))
    print(f"  {'presets.json':14} {len(presets):>7} presets -> PRESETS")

    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"\nwrote {OUT.relative_to(HERE.parent.parent)} "
          f"({OUT.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
