// foodmarket.js — Food & Market's kitchens, doodles and badges, on the server.
//
// On the platform these live in its `index.html` as `_foodMarket*` helpers keyed on the
// tenant slug, and run in the browser on every render. Here they are the same rules,
// copied, run once where the markup is built - so a diner's phone gets finished cards.
//
// A page is Food & Market when its tenant setting `platform_tenant` is
// "food-market-main": that is the `data-tenant` its stylesheet (`minimal_sushi.css`,
// generated by `menu/render/extract_food_market.py`) is scoped to - the same alias the
// platform uses for its own F&M test copy.

export const FM_TENANT = "food-market-main";
export const isFoodMarket = (cfg = {}) => cfg.platform_tenant === FM_TENANT;

export const KITCHENS = ["georgian", "thai", "japanese", "drinks"];
export const KITCHEN_LABELS = {
  en: { georgian: "Georgian & More", thai: "Thai", japanese: "Japanese", drinks: "Drinks" },
  ka: { georgian: "ქართული და სხვა", thai: "ტაილანდური", japanese: "იაპონური", drinks: "სასმელები" },
};

/** The kitchen a category belongs to, from its English name's prefix (`_groupOf`). */
export function kitchenOf(catName) {
  const prefix = String(catName || "").split("—")[0].trim();
  if (prefix === "Drinks") return "drinks";
  if (prefix === "Thai") return "thai";
  if (prefix === "Japanese") return "japanese";
  return "georgian";
}

/** "Georgian — Pizza" reads "Pizza" once you are inside the Georgian kitchen. */
export function visibleCategory(name) {
  return String(name || "").trim()
    .replace(/^(?:Georgian|Thai|Japanese|Drinks|ქართული|ტაილანდური|იაპონური|სასმელები)\s+—\s+/, "");
}

const GEORGIAN_DOODLES = ["pg-shaman", "pg-eye-legs", "pg-diver", "pg-totem", "pg-deer-star",
  "pg-deer-running", "pg-sun", "pg-hunter", "pg-wrestler", "pg-duel", "pg-raised-hands", "pg-river"];
const THAI_DOODLES = ["th-sun-burst", "th-flower", "th-star", "th-chili"];
const JAPANESE_CARD_DOODLES = ["jp-crane"];
const DRINKS_DOODLES = ["dr-citrus", "dr-flower", "dr-spiral", "dr-swirl"];
const JAPANESE_KANJI = {
  "Japanese — Sashimi": "刺身",
  "Japanese — Nigiri": "握り寿司",
  "Japanese — Onigiri": "お握り",
  "Japanese — Maki": "巻き",
  "Japanese — Uramaki Roll": "裏巻き",
  "Japanese — Futomaki": "太巻き",
};

/** A category heading's doodle or kanji (`_foodMarketCategoryDecoration`). */
export function categoryDecoration(name) {
  const clean = String(name || "");
  const prefix = clean.split("—")[0].trim();
  if (prefix === "Japanese") {
    const kanji = JAPANESE_KANJI[clean];
    return kanji ? { kanji } : {};
  }
  const icons = prefix === "Georgian" ? GEORGIAN_DOODLES
    : prefix === "Thai" ? THAI_DOODLES
    : prefix === "Drinks" ? DRINKS_DOODLES
    : null;
  if (!icons) return {};
  let hash = 0;
  for (let i = 0; i < clean.length; i++) hash = (hash * 31 + clean.charCodeAt(i)) >>> 0;
  return { doodle: icons[hash % icons.length] };
}

/** The faint doodle stamped on ~3 in 5 cards (`_foodMarketCardDoodle`). */
export function cardDoodle(globalIdx, kitchen) {
  const pool = kitchen === "georgian" ? GEORGIAN_DOODLES
    : kitchen === "thai" ? THAI_DOODLES
    : kitchen === "japanese" ? JAPANESE_CARD_DOODLES
    : kitchen === "drinks" ? DRINKS_DOODLES
    : null;
  if (!pool) return null;
  const hash = Math.imul(globalIdx + 1, 2654435761) >>> 0;
  if (hash % 5 >= 3) return null;
  return pool[Math.floor(hash / 5) % pool.length];
}

// The pepper / leaf printed beside these exact dishes on F&M's paper menus. Keyed by the
// English name, as the platform keys them.
const SPICY = new Set([
  "Stir Fried Cashewnut", "Sriracha Fried Rice", "Rice with Grilled Chicken & Satay Sauce",
  "Grilled Chicken Salad", "Crispy Chicken Salad", "Kimchi", "Panang Curry", "Massaman Curry",
  "Grilled Chicken Red Hot Curry", "Green Curry", "Yellow Curry", "Stir fried Noodles Sriracha Sauce",
  "Pad Thai Noodles", "Tom Yum Seafood Clear Soup", "Tom Yum", "Tom Kha", "Tom Yum Ramen with Shrimp",
  "Salmon Poke Bowl", "Spicy Salmon", "Spicy Tuna", "Spicy Philadelphia",
]);
const VEGGIE = new Set([
  "MARGHERITA", "VEGETARIAN", "PENNE ARRABIATA", "MUSHROOM & TRUFFLE FUSILLONI",
  "Thai Style Fried Rice", "Stir fried Glass Noodles", "Pad Si Euw", "Pad Thai Noodles",
  "Veggie Futomaki",
]);

export function dietBadges(nameEn) {
  let out = "";
  if (SPICY.has(nameEn)) out += '<span class="fm-diet-badge" title="Spicy" aria-label="Spicy">🌶️</span>';
  if (VEGGIE.has(nameEn)) out += '<span class="fm-diet-badge" title="Vegetarian" aria-label="Vegetarian">🌱</span>';
  return out;
}

/** The kitchen a diner lands in: `?menu=` when it names one, otherwise none (the picker). */
export function kitchenFromQuery(url) {
  const v = url.searchParams.get("menu");
  return KITCHENS.includes(v) ? v : null;
}

/** Kitchen tabs above the category pills (`_renderGroupToggle`). */
export function kitchenTabs(active, lang) {
  const lab = KITCHEN_LABELS[lang] || KITCHEN_LABELS.en;
  return `<div id="menu-groups" class="menu-groups">` + KITCHENS.map((g) =>
    `<button class="group-btn${g === active ? " active" : ""}" data-group="${g}">` +
    (g === "japanese"
      ? `<span class="fm-tab-crane" aria-hidden="true"></span><span>${lab[g]}</span>`
      : lab[g]) +
    `</button>`).join("") + `</div>`;
}
